# NODE API FOR RESTAURANTS

services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    networks:
      - node-mongo
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=password
      - MONGO_HOST=mongo-server
      - MONGO_PORT=27017
      - MONGO_DB=restaurants
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  mongo:
    command: mongod --quiet --logpath /dev/null
    image: mongo
    container_name: mongo-server
    ports:
      - "27017:27017"
    networks:
      - node-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=restaurants
    volumes:
      - ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


networks:
  node-mongo:
    driver: bridge